baseURL = "https://iii-cutting-edge-tech-lab.github.io"
languageCode = "en-us"
title = "Hugo Grayscale Theme"
theme = "hugograyscale"
enableInlineShortcodes = true

#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"

[Author]
    name = "iii-cutting-edge-tech-lab"
    email = ""

[Social]
    twitter = "neilkuan"
